/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AlarmEvent
         * @description One record per alarm episode, written by the R2 observer on
         *     alarm.py's on_transition hook. presence_during is the RAW radar verdict
         *     for the episode (R2 rule), never PresenceState.mode.
         */
        AlarmEvent: {
            /**
             * Ack Source
             * @default null
             */
            ack_source: ("device" | "app") | null;
            /**
             * Acknowledged At
             * @default null
             */
            acknowledged_at: string | null;
            /**
             * Crossed Actual
             * @default false
             */
            crossed_actual: boolean;
            /**
             * Escalated
             * @default false
             */
            escalated: boolean;
            /** Event Id */
            event_id: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /**
             * Presence During
             * @default unknown
             * @enum {string}
             */
            presence_during: "home" | "away" | "unknown";
            /**
             * Rearm Count
             * @default 0
             */
            rearm_count: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Tier
             * @enum {string}
             */
            tier: "predicted_low" | "actual_low" | "stale" | "high";
        };
        /** AlarmState */
        AlarmState: {
            /**
             * Acknowledged At
             * @default null
             */
            acknowledged_at: string | null;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * State
             * @default idle
             * @enum {string}
             */
            state: "idle" | "pending" | "active" | "acknowledged" | "rearmed";
            /**
             * Trigger Type
             * @default null
             */
            trigger_type: ("predicted_low" | "actual_low" | "high" | "stale") | null;
        };
        /** AvailabilitySlot */
        AvailabilitySlot: {
            /** End */
            end: string;
            /** Start */
            start: string;
            /** Weekday */
            weekday: number;
        };
        /**
         * BuddyAlert
         * @description Never carries a glucose value, a location, or a contact (invariant 15).
         */
        BuddyAlert: {
            /** Alert Id */
            alert_id: string;
            /**
             * Audio Url
             * @default null
             */
            audio_url: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "device_confirmed" | "unconfirmed";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Event Id */
            event_id: string;
            /** Status */
            status: string;
            /** Urgency */
            urgency: number;
        };
        /** BuddyLink */
        BuddyLink: {
            /** First Name */
            first_name: string;
            /** Link Id */
            link_id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "twin" | "mirror";
            /** Peer Id */
            peer_id: string;
            /** State */
            state: string;
        };
        /** BuddyMatch */
        BuddyMatch: {
            /** Candidate Id */
            candidate_id: string;
            /** Hours Covered */
            hours_covered: number;
            /** Match Id */
            match_id: string;
            /** Mirror */
            mirror: boolean;
            /** Score */
            score: number;
            /** Shared Languages */
            shared_languages?: string[];
            /**
             * Status
             * @default offered
             * @enum {string}
             */
            status: "offered" | "accepted" | "declined";
            /** User Id */
            user_id: string;
        };
        /**
         * CgmFeed
         * @description Verified once at signup, never streamed; the relay holds no readings.
         */
        CgmFeed: {
            /** Nightscout Url */
            nightscout_url: string;
            /** Token */
            token: string;
        };
        /**
         * DevicePairing
         * @description The OWNER pairing (R5+): phone app <-> Pi through the relay. Separate
         *     from Pairing, whose peer_kind stays doctor | buddy. The token travels only
         *     in the QR or the typed code, never in a URL query.
         */
        DevicePairing: {
            /** Device Id */
            device_id: string;
            /** Device Url */
            device_url: string;
            /**
             * Paired At
             * @default null
             */
            paired_at: string | null;
            /**
             * State
             * @default pending
             * @enum {string}
             */
            state: "pending" | "paired" | "revoked";
            /** Token */
            token: string;
            /** User Id */
            user_id: string;
        };
        /**
         * DoctorMessage
         * @description Applies only after patient echo-and-confirm (invariant 8). Decline,
         *     24 h expiry, and silence apply nothing.
         */
        DoctorMessage: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Hold Weeks
             * @default null
             */
            hold_weeks: number | null;
            /**
             * Insulin
             * @default null
             */
            insulin: ("basal" | "bolus") | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "plan_create" | "plan_update" | "proceed" | "hold_step" | "insulin_change" | "note" | "schedule_request" | "end_watch" | "dismiss";
            /** Message Id */
            message_id: string;
            /**
             * New Units
             * @default null
             */
            new_units: number | null;
            /** @default null */
            plan: components["schemas"]["TitrationPlan"] | null;
            /**
             * Plan Id
             * @default null
             */
            plan_id: string | null;
            /**
             * Start Date
             * @default null
             */
            start_date: string | null;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "confirmed" | "declined" | "expired";
            /**
             * Text
             * @default null
             */
            text: string | null;
        };
        /** EmergencyScript */
        EmergencyScript: {
            /** Steps */
            steps?: string[];
        };
        /** FamilyBearer */
        FamilyBearer: {
            /** Bearer Id */
            bearer_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Recipient Id */
            recipient_id: string;
            /**
             * Revoked At
             * @default null
             */
            revoked_at: string | null;
            /** Token Hash */
            token_hash: string;
        };
        /** FamilyRecipient */
        FamilyRecipient: {
            /** Email */
            email: string;
            /**
             * First Story Approved
             * @default false
             */
            first_story_approved: boolean;
            /**
             * Level
             * @default story_only
             * @enum {string}
             */
            level: "story_only" | "story_and_view";
            /** Name */
            name: string;
            /** Recipient Id */
            recipient_id: string;
            /**
             * Send Mode
             * @default approve_each
             * @enum {string}
             */
            send_mode: "automatic" | "approve_each";
            /**
             * State
             * @default active
             * @enum {string}
             */
            state: "active" | "paused" | "revoked";
        };
        /**
         * FamilyStory
         * @description Level story_only never contains a glucose value; a demo story is
         *     never emailed (invariant 19).
         */
        FamilyStory: {
            /**
             * Audio Url
             * @default null
             */
            audio_url: string | null;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /**
             * Level
             * @enum {string}
             */
            level: "story_only" | "story_and_view";
            /**
             * Night Date
             * Format: date
             */
            night_date: string;
            /** Recipient Id */
            recipient_id: string;
            /**
             * Sent At
             * @default null
             */
            sent_at: string | null;
            /**
             * Status
             * @default pending_approval
             * @enum {string}
             */
            status: "pending_approval" | "sent" | "skipped" | "failed" | "demo";
            /** Story Id */
            story_id: string;
            /** Text */
            text: string;
        };
        /** Forecast */
        Forecast: {
            /**
             * Horizon Min
             * @default 30
             */
            horizon_min: number;
            /** Predicted Mgdl */
            predicted_mgdl: number;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** HubClaim */
        HubClaim: {
            /** Actions */
            actions?: string[];
            /** Claim Id */
            claim_id: string;
            /**
             * Claimed At
             * Format: date-time
             */
            claimed_at: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Listing Id */
            listing_id: string;
            /**
             * Outcome
             * @default null
             */
            outcome: string | null;
            /** Volunteer Id */
            volunteer_id: string;
        };
        /** HubListing */
        HubListing: {
            /**
             * Claim Expires At
             * @default null
             */
            claim_expires_at: string | null;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "device_confirmed" | "unconfirmed";
            /** Elapsed Min */
            elapsed_min: number;
            /** First Name */
            first_name: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /** Listing Id */
            listing_id: string;
            /**
             * Status
             * @default open
             * @enum {string}
             */
            status: "open" | "claimed" | "treating" | "resolved";
            /**
             * Treating Expires At
             * @default null
             */
            treating_expires_at: string | null;
            /** Urgency */
            urgency: number;
        };
        /** LowEvent */
        LowEvent: {
            /**
             * Alarm Event Id
             * @default null
             */
            alarm_event_id: string | null;
            /** Auc Below 70 */
            auc_below_70: number;
            /**
             * Carbs Logged Within 30Min
             * @default false
             */
            carbs_logged_within_30min: boolean;
            /**
             * Inferred Unfelt
             * @default false
             */
            inferred_unfelt: boolean;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /** Low Event Id */
            low_event_id: string;
            /** Minutes Below 70 */
            minutes_below_70: number;
            /**
             * Nadir At
             * Format: date-time
             */
            nadir_at: string;
            /** Nadir Mgdl */
            nadir_mgdl: number;
            /**
             * Night Date
             * Format: date
             */
            night_date: string;
            /**
             * Recovery Slope
             * @default null
             */
            recovery_slope: number | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
        };
        /**
         * LowEventRecall
         * @description answer=None after the morning window is reported as "no answer",
         *     never fine; it never enters the unfelt-low denominator.
         */
        LowEventRecall: {
            /**
             * Answer
             * @default null
             */
            answer: ("felt_and_treated" | "woke_no_symptoms" | "dont_remember" | "was_awake") | null;
            /**
             * Answered At
             * @default null
             */
            answered_at: string | null;
            /**
             * Asked At
             * Format: date-time
             */
            asked_at: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /** Low Event Id */
            low_event_id: string;
        };
        /** MorningReport */
        MorningReport: {
            /**
             * Audio Url
             * @default null
             */
            audio_url: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /**
             * Graph Png Path
             * @default null
             */
            graph_png_path: string | null;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /** Narrative */
            narrative: string;
            /**
             * Night Date
             * Format: date
             */
            night_date: string;
            /** Report Id */
            report_id: string;
            /** Stats */
            stats?: {
                [key: string]: unknown;
            };
        };
        /** NarrativeScope */
        NarrativeScope: {
            /**
             * Backboard Assistant Id
             * @default null
             */
            backboard_assistant_id: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "patient" | "doctor" | "buddy" | "family";
            /** Scope Id */
            scope_id: string;
            /**
             * Thread Id
             * @default null
             */
            thread_id: string | null;
        };
        /** NightBuddyOptIns */
        NightBuddyOptIns: {
            /**
             * Be Watcher
             * @default false
             */
            be_watcher: boolean;
            /**
             * Have Buddy
             * @default false
             */
            have_buddy: boolean;
            /**
             * Hub Volunteer
             * @default false
             */
            hub_volunteer: boolean;
            /**
             * Hub Watchable
             * @default false
             */
            hub_watchable: boolean;
        };
        /** NightRecord */
        NightRecord: {
            /** Alarm Event Ids */
            alarm_event_ids?: string[];
            /**
             * Code Source
             * @enum {string}
             */
            code_source: "logged" | "inferred" | "unknown";
            /** Coverage Pct */
            coverage_pct: number;
            /**
             * Dawn Rise Mgdl
             * @default null
             */
            dawn_rise_mgdl: number | null;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /**
             * Level2 Count
             * @default 0
             */
            level2_count: number;
            /**
             * Low Point Mgdl
             * @default null
             */
            low_point_mgdl: number | null;
            /**
             * Minutes Below 70
             * @default 0
             */
            minutes_below_70: number;
            /**
             * Near Miss Count
             * @default 0
             */
            near_miss_count: number;
            /**
             * Night Date
             * Format: date
             */
            night_date: string;
            /** Reason Codes */
            reason_codes: string[];
            /**
             * Rise Mgdl
             * @default null
             */
            rise_mgdl: number | null;
            /**
             * Tbr Pct
             * @default null
             */
            tbr_pct: number | null;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /**
         * Pairing
         * @description The doctor or buddy pairing (the crypto handshake, R5). The OWNER
         *     pairing is DevicePairing below, a separate model.
         */
        Pairing: {
            /**
             * Confirmed At
             * @default null
             */
            confirmed_at: string | null;
            /** Device Id */
            device_id: string;
            /** Doctor Display Name */
            doctor_display_name: string;
            /** Doctor Id */
            doctor_id: string;
            /** Doctor Pk */
            doctor_pk: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /**
             * Peer Kind
             * @default doctor
             * @enum {string}
             */
            peer_kind: "doctor" | "buddy";
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "paired" | "revoked";
        };
        /** PresenceState */
        PresenceState: {
            /**
             * Mode
             * @default home
             * @enum {string}
             */
            mode: "home" | "away";
            /**
             * Since
             * Format: date-time
             */
            since: string;
            /**
             * Source
             * @default radar
             * @enum {string}
             */
            source: "radar" | "toggle";
        };
        /** Reading */
        Reading: {
            /** Glucose Mgdl */
            glucose_mgdl: number;
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
            /**
             * Source
             * @enum {string}
             */
            source: "nightscout" | "replay";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Trend */
            trend: string;
        };
        /** SecondOpinion */
        SecondOpinion: {
            /** Advice */
            advice: boolean;
            /** Invented Number */
            invented_number: boolean;
        };
        /** Settings */
        Settings: {
            /**
             * Basal Time
             * @default null
             */
            basal_time: string | null;
            /**
             * Basal Units
             * @default null
             */
            basal_units: number | null;
            /**
             * Consecutive Predictions N
             * @default 2
             */
            consecutive_predictions_n: number;
            /** @default null */
            emergency_script: components["schemas"]["EmergencyScript"] | null;
            /** Family Recipients */
            family_recipients?: components["schemas"]["FamilyRecipient"][];
            /**
             * Glucagon Expiry
             * @default null
             */
            glucagon_expiry: string | null;
            /**
             * Glucagon On Hand
             * @default null
             */
            glucagon_on_hand: boolean | null;
            /**
             * High Alert Mode
             * @default oneshot
             * @enum {string}
             */
            high_alert_mode: "oneshot" | "remind";
            /**
             * High Remind Hours
             * @default null
             */
            high_remind_hours: number | null;
            /**
             * High Threshold
             * @default 250
             */
            high_threshold: number;
            /**
             * Iob Duration Hours
             * @default 4
             */
            iob_duration_hours: number;
            /** Led Colors */
            led_colors?: {
                [key: string]: string;
            };
            /**
             * Low Threshold
             * @default 70
             */
            low_threshold: number;
            night_buddy?: components["schemas"]["NightBuddyOptIns"];
            /**
             * Night Window End
             * @default 07:00
             */
            night_window_end: string;
            /**
             * Night Window Start
             * @default 22:00
             */
            night_window_start: string;
            /**
             * Predictive Enabled
             * @default true
             */
            predictive_enabled: boolean;
            /**
             * Predictive Lead Min
             * @default 30
             */
            predictive_lead_min: number;
            /**
             * Presence Override
             * @default auto
             * @enum {string}
             */
            presence_override: "auto" | "home" | "away";
            /**
             * Report Email
             * @default null
             */
            report_email: string | null;
            /**
             * Sound
             * @default alarm_soft
             */
            sound: string;
            /**
             * Volume
             * @default 0.8
             */
            volume: number;
        };
        /**
         * SignalCard
         * @description Clinical Signal Card v0 (published in relay/README.md). One schema,
         *     two programs; `program` decides which sections a renderer shows. Every
         *     metric carries a confidence label; a card never shows a blank row; a
         *     card never contains a dose recommendation.
         */
        SignalCard: {
            /** Allowed Actions */
            allowed_actions?: string[];
            /** Card Id */
            card_id: string;
            /** Confidence */
            confidence?: {
                [key: string]: "measured" | "reported" | "inferred";
            };
            /** Excluded Counts */
            excluded_counts?: {
                [key: string]: number;
            };
            /** Flags */
            flags?: ("lows" | "highs" | "awareness" | "tolerance" | "level2" | "rearm" | "ketone_risk" | "baseline_thin" | "dose_mismatch" | "missed_injection" | "rise_high" | "rise_low")[];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Headline */
            headline: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "basal_check" | "hypo_response" | "follow_up" | "early_check" | "step_check" | "step_gate" | "safety" | "graduation" | "baseline_note";
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Narrative */
            narrative: string;
            /** Nights */
            nights?: {
                [key: string]: unknown;
            }[];
            /** Patient Pseudonym */
            patient_pseudonym: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            /**
             * Plan Id
             * @default null
             */
            plan_id: string | null;
            /**
             * Program
             * @enum {string}
             */
            program: "standing" | "step_watch";
            /** Resource Categories */
            resource_categories?: string[];
            /**
             * Schema Version
             * @default 0
             */
            schema_version: string;
            /**
             * Source
             * @enum {string}
             */
            source: "irin_bedside" | "irin_brain";
            /**
             * Status
             * @enum {string}
             */
            status: "green" | "amber" | "red" | "insufficient";
            /**
             * Step Index
             * @default null
             */
            step_index: number | null;
            /** Tolerance Days */
            tolerance_days?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * StateSnapshot
         * @description The payload of a state_snapshot message, sent by the ws hub on every
         *     new connection. Clients render from snapshot + updates, never from
         *     assumed history.
         */
        StateSnapshot: {
            /** @default null */
            active_plan: components["schemas"]["TitrationPlan"] | null;
            alarm?: components["schemas"]["AlarmState"];
            /** Buddy State */
            buddy_state?: {
                [key: string]: unknown;
            };
            /**
             * Clock Synced
             * @default true
             */
            clock_synced: boolean;
            /** Family Story Status */
            family_story_status?: {
                [key: string]: unknown;
            }[];
            /** @default null */
            forecast: components["schemas"]["Forecast"] | null;
            /** @default null */
            latest_reading: components["schemas"]["Reading"] | null;
            /**
             * Mode
             * @default replay
             * @enum {string}
             */
            mode: "replay" | "nightscout";
            /** Pairing State */
            pairing_state?: {
                [key: string]: unknown;
            };
            /** Pending Doctor Messages */
            pending_doctor_messages?: components["schemas"]["DoctorMessage"][];
            /** @default null */
            presence: components["schemas"]["PresenceState"] | null;
            settings?: components["schemas"]["Settings"];
            /** Todays Checkin Status */
            todays_checkin_status?: {
                [key: string]: unknown;
            };
        };
        /** SymptomCheck */
        SymptomCheck: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Gi
             * @enum {string}
             */
            gi: "fine" | "rough" | "cant_eat";
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
        };
        /** TitrationPlan */
        TitrationPlan: {
            /**
             * Drug Class
             * @enum {string}
             */
            drug_class: "glp1" | "gip_glp1" | "weekly_basal";
            /** Drug Label */
            drug_label: string;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
            /** On Insulin */
            on_insulin: boolean;
            options?: components["schemas"]["WatchOptions"];
            /** Plan Id */
            plan_id: string;
            /**
             * Started At
             * Format: date
             */
            started_at: string;
            /**
             * Status
             * @default pending_confirm
             * @enum {string}
             */
            status: "pending_confirm" | "active" | "graduated" | "ended";
            /** Steps */
            steps: components["schemas"]["TitrationStep"][];
        };
        /** TitrationStep */
        TitrationStep: {
            /** Dose Label */
            dose_label: string;
            /** Index */
            index: number;
            /**
             * Planned Start
             * Format: date
             */
            planned_start: string;
        };
        /**
         * Treatment
         * @description A logged event. Invariant 2: insulin_units may only be stored with
         *     confirmed=True (echo-and-confirm). A parsed-but-unconfirmed voice entry
         *     lives in voice.py's pending state, never in a Treatment.
         */
        Treatment: {
            /**
             * Carbs G
             * @default null
             */
            carbs_g: number | null;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
            /**
             * Dose Label
             * @default null
             */
            dose_label: string | null;
            /**
             * Insulin Units
             * @default null
             */
            insulin_units: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "bolus" | "basal" | "carbs" | "note" | "glp1_dose" | "therapy_change";
            /**
             * Text
             * @default null
             */
            text: string | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Availability */
            availability?: components["schemas"]["AvailabilitySlot"][];
            /** @default null */
            cgm_feed: components["schemas"]["CgmFeed"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Emergency Contact Ciphertext
             * @default null
             */
            emergency_contact_ciphertext: string | null;
            emergency_script?: components["schemas"]["EmergencyScript"];
            /** First Name */
            first_name: string;
            /** Languages */
            languages?: string[];
            optins?: components["schemas"]["NightBuddyOptIns"];
            /**
             * Sleep Window
             * @default [
             *       "22:00",
             *       "08:00"
             *     ]
             */
            sleep_window: [
                string,
                string
            ];
            /** Timezones */
            timezones?: string[];
            /** User Id */
            user_id: string;
            /** Username */
            username: string;
        };
        /** WSMessage */
        WSMessage: {
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /**
             * Type
             * @enum {string}
             */
            type: "reading_update" | "forecast_update" | "alarm_state_change" | "acknowledge" | "settings_change" | "treatment_logged" | "presence_change" | "mode_change" | "state_snapshot" | "card_sent" | "doctor_message_received" | "doctor_message_resolved" | "recall_due" | "symptom_check_due" | "pairing_state" | "plan_state" | "buddy_alert" | "hub_update" | "treating_set" | "family_story_pending" | "family_story_sent";
        };
        /** WatchOptions */
        WatchOptions: {
            /**
             * Ketone Prompts
             * @default false
             */
            ketone_prompts: boolean;
            /**
             * Step Week Vigilance
             * @default false
             */
            step_week_vigilance: boolean;
            /**
             * Vigilance Offset Mgdl
             * @default 10
             */
            vigilance_offset_mgdl: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
