/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_api_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History
         * @description Readings from the last `minutes` of clock time, oldest first (the
         *     display's graph after a reload; Justin's request, no contracts change).
         */
        get: operations["history_api_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast Status
         * @description The last forecast result: forecast, status (ok | suspended | unavailable), reason.
         */
        get: operations["forecast_status_api_forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/fresh_pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fresh Pin
         * @description The one list of fresh-PIN endpoints, read by display.js and the app's usePin hook.
         */
        get: operations["fresh_pin_api_contracts_fresh_pin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Mode
         * @description Swap the active datasource at runtime (chris.md step 12). Day one: the
         *     swap mechanism; alarm reset is wired here as the alarm engine lands. On
         *     return to live the poller serves the cached reading marked stale until a
         *     fresh poll lands.
         */
        post: operations["set_mode_api_mode_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge
         * @description Acknowledge the current alarm. source records which screen answered
         *     (the kiosk's big button = device, the app = app) for the R2 recorder.
         */
        post: operations["acknowledge_api_acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/log/voice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Voice
         * @description Parse spoken text. Carbs-only entries are stored at once; any insulin
         *     comes back as needs_confirm with an echo and a pending_id (10 s on clock.py).
         */
        post: operations["log_voice_api_log_voice_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/log/voice/{pending_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Voice Confirm */
        post: operations["log_voice_confirm_api_log_voice__pending_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/log/voice/{pending_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Voice Cancel */
        post: operations["log_voice_cancel_api_log_voice__pending_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log Treatment
         * @description Structured logging from the app's forms (basal taken, carbs + units,
         *     notes). The Treatment contract refuses insulin_units without
         *     confirmed=True (422); `confirmed` is the client's assertion that its
         *     echo-and-confirm screen was passed, which the server cannot see, so the
         *     PIN gate is what makes that assertion trustworthy.
         */
        post: operations["log_treatment_api_log_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/treatments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Treatments */
        get: operations["treatments_api_treatments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Presence State */
        get: operations["presence_state_api_presence_get"];
        put?: never;
        /**
         * Set Presence
         * @description The manual Home/Away toggle (Settings.presence_override). It always beats
         *     the radar; it gates room outputs only and never touches alarm logic.
         */
        post: operations["set_presence_api_presence_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forwarder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forwarder State
         * @description The cloud forwarder: enabled, cursor, batches sent, failures (the under-the-hood panel).
         */
        get: operations["forwarder_state_api_forwarder_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scheduler State
         * @description clock_synced (the NTP guard), display_mode (detail | night | morning, from
         *     backend state), and the basal nudge (none | visual | email).
         */
        get: operations["scheduler_state_api_scheduler_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alarm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alarm State */
        get: operations["alarm_state_api_alarm_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        put?: never;
        /**
         * Update Settings
         * @description Merge the given fields into the live settings (a partial body is fine;
         *     nested objects merge field by field, lists replace whole). The alarm
         *     engine, presence machine, scheduler, and report builder all hold the
         *     same Settings object, so they see the change at once.
         */
        post: operations["update_settings_api_settings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reports
         * @description Newest night first; every report carries is_demo.
         */
        get: operations["list_reports_api_reports_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Report */
        get: operations["latest_report_api_reports_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{night_date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_reports__night_date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/{night_date}/graph.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report Graph */
        get: operations["report_graph_api_reports__night_date__graph_png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Build Report
         * @description Build (or rebuild) a report now: the demo panel's button and the
         *     pre-generated fallback for the no-network demo.
         */
        post: operations["build_report_api_reports_build_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Scenarios
         * @description Read-only, any mode: the CSVs a demo may play.
         */
        get: operations["list_scenarios_api_demo_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/scenario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Select Scenario
         * @description Play another scenario CSV from its first row (clock reset to its start).
         */
        post: operations["select_scenario_api_demo_scenario_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/speed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Speed
         * @description Change the replay multiplier without moving the clock.
         */
        post: operations["set_speed_api_demo_speed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Pause Feed
         * @description Pause the FEED (the sensor stops), not the clock: after 15 clock
         *     minutes the reading is shown stale, the honest outcome.
         */
        post: operations["pause_feed_api_demo_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/inject_low": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject Low
         * @description Overlay one reading at the current clock time (at the pause moment while
         *     paused, so it shows at once); the CSV stays clean.
         */
        post: operations["inject_low_api_demo_inject_low_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demo/basal_time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Basal Time Button
         * @description Set basal_time to 61 clock minutes ago so the basal nudge shows at once.
         *     The live value is stashed and restored on the switch back to live.
         */
        post: operations["basal_time_button_api_demo_basal_time_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AckRequest */
        AckRequest: {
            /**
             * Source
             * @enum {string}
             */
            source: "device" | "app";
        };
        /** AlarmState */
        AlarmState: {
            /**
             * State
             * @default idle
             * @enum {string}
             */
            state: "idle" | "pending" | "active" | "acknowledged" | "rearmed";
            /** Trigger Type */
            trigger_type?: ("predicted_low" | "actual_low" | "high" | "stale") | null;
            /** Started At */
            started_at?: string | null;
            /** Acknowledged At */
            acknowledged_at?: string | null;
        };
        /** BuildReportRequest */
        BuildReportRequest: {
            /** Night Date */
            night_date?: string | null;
        };
        /** EmergencyScript */
        EmergencyScript: {
            /** Steps */
            steps?: string[];
        };
        /** FamilyRecipient */
        FamilyRecipient: {
            /** Recipient Id */
            recipient_id: string;
            /** Name */
            name: string;
            /** Email */
            email: string;
            /**
             * Level
             * @default story_only
             * @enum {string}
             */
            level: "story_only" | "story_and_view";
            /**
             * Send Mode
             * @default approve_each
             * @enum {string}
             */
            send_mode: "automatic" | "approve_each";
            /**
             * State
             * @default active
             * @enum {string}
             */
            state: "active" | "paused" | "revoked";
            /**
             * First Story Approved
             * @default false
             */
            first_story_approved: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InjectRequest */
        InjectRequest: {
            /** Glucose Mgdl */
            glucose_mgdl: number;
            /**
             * Trend
             * @default SingleDown
             */
            trend: string;
        };
        /** ModeRequest */
        ModeRequest: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "replay" | "nightscout";
        };
        /** MorningReport */
        MorningReport: {
            /** Report Id */
            report_id: string;
            /**
             * Night Date
             * Format: date
             */
            night_date: string;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Stats */
            stats?: {
                [key: string]: unknown;
            };
            /** Narrative */
            narrative: string;
            /** Graph Png Path */
            graph_png_path?: string | null;
            /** Audio Url */
            audio_url?: string | null;
            /**
             * Is Demo
             * @default false
             */
            is_demo: boolean;
        };
        /** NightBuddyOptIns */
        NightBuddyOptIns: {
            /**
             * Have Buddy
             * @default false
             */
            have_buddy: boolean;
            /**
             * Be Watcher
             * @default false
             */
            be_watcher: boolean;
            /**
             * Hub Watchable
             * @default false
             */
            hub_watchable: boolean;
            /**
             * Hub Volunteer
             * @default false
             */
            hub_volunteer: boolean;
        };
        /** PauseRequest */
        PauseRequest: {
            /** Paused */
            paused: boolean;
        };
        /** PresenceOverride */
        PresenceOverride: {
            /**
             * Override
             * @enum {string}
             */
            override: "auto" | "home" | "away";
        };
        /** PresenceState */
        PresenceState: {
            /**
             * Mode
             * @default home
             * @enum {string}
             */
            mode: "home" | "away";
            /**
             * Source
             * @default radar
             * @enum {string}
             */
            source: "radar" | "toggle";
            /**
             * Since
             * Format: date-time
             */
            since: string;
        };
        /** Reading */
        Reading: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Glucose Mgdl */
            glucose_mgdl: number;
            /** Trend */
            trend: string;
            /**
             * Source
             * @enum {string}
             */
            source: "nightscout" | "replay";
            /**
             * Is Stale
             * @default false
             */
            is_stale: boolean;
        };
        /** ScenarioRequest */
        ScenarioRequest: {
            /** Name */
            name: string;
        };
        /** Settings */
        Settings: {
            /**
             * Low Threshold
             * @default 70
             */
            low_threshold: number;
            /**
             * High Threshold
             * @default 250
             */
            high_threshold: number;
            /**
             * Predictive Enabled
             * @default true
             */
            predictive_enabled: boolean;
            /**
             * Predictive Lead Min
             * @default 30
             */
            predictive_lead_min: number;
            /**
             * Consecutive Predictions N
             * @default 2
             */
            consecutive_predictions_n: number;
            /**
             * Night Window Start
             * @default 22:00
             */
            night_window_start: string;
            /**
             * Night Window End
             * @default 07:00
             */
            night_window_end: string;
            /**
             * High Alert Mode
             * @default oneshot
             * @enum {string}
             */
            high_alert_mode: "oneshot" | "remind";
            /** High Remind Hours */
            high_remind_hours?: number | null;
            /** Led Colors */
            led_colors?: {
                [key: string]: string;
            };
            /**
             * Sound
             * @default alarm_soft
             */
            sound: string;
            /**
             * Volume
             * @default 0.8
             */
            volume: number;
            /** Report Email */
            report_email?: string | null;
            /** Basal Time */
            basal_time?: string | null;
            /**
             * Iob Duration Hours
             * @default 4
             */
            iob_duration_hours: number;
            /**
             * Presence Override
             * @default auto
             * @enum {string}
             */
            presence_override: "auto" | "home" | "away";
            /** Basal Units */
            basal_units?: number | null;
            /** Glucagon On Hand */
            glucagon_on_hand?: boolean | null;
            /** Glucagon Expiry */
            glucagon_expiry?: string | null;
            night_buddy?: components["schemas"]["NightBuddyOptIns"];
            emergency_script?: components["schemas"]["EmergencyScript"] | null;
            /** Family Recipients */
            family_recipients?: components["schemas"]["FamilyRecipient"][];
        };
        /** SpeedRequest */
        SpeedRequest: {
            /** Speed */
            speed: number;
        };
        /**
         * Treatment
         * @description A logged event. Invariant 2: insulin_units may only be stored with
         *     confirmed=True (echo-and-confirm). A parsed-but-unconfirmed voice entry
         *     lives in voice.py's pending state, never in a Treatment.
         */
        Treatment: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "bolus" | "basal" | "carbs" | "note" | "glp1_dose" | "therapy_change";
            /** Insulin Units */
            insulin_units?: number | null;
            /** Carbs G */
            carbs_g?: number | null;
            /** Dose Label */
            dose_label?: string | null;
            /** Text */
            text?: string | null;
            /**
             * Confirmed
             * @default false
             */
            confirmed: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceText */
        VoiceText: {
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    latest_api_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reading"];
                };
            };
        };
    };
    history_api_history_get: {
        parameters: {
            query?: {
                minutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reading"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forecast_status_api_forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    fresh_pin_api_contracts_fresh_pin_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    set_mode_api_mode_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_api_acknowledge_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_voice_api_log_voice_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceText"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_voice_confirm_api_log_voice__pending_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path: {
                pending_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_voice_cancel_api_log_voice__pending_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path: {
                pending_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_treatment_api_log_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Treatment"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    treatments_api_treatments_get: {
        parameters: {
            query?: {
                hours?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Treatment"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presence_state_api_presence_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresenceState"];
                };
            };
        };
    };
    set_presence_api_presence_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresenceOverride"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresenceState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    forwarder_state_api_forwarder_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    scheduler_state_api_scheduler_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    alarm_state_api_alarm_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlarmState"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
        };
    };
    update_settings_api_settings_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_reports_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MorningReport"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_report_api_reports_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MorningReport"];
                };
            };
        };
    };
    get_report_api_reports__night_date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                night_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MorningReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_graph_api_reports__night_date__graph_png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                night_date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    build_report_api_reports_build_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BuildReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MorningReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_demo_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    select_scenario_api_demo_scenario_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_speed_api_demo_speed_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_feed_api_demo_pause_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PauseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inject_low_api_demo_inject_low_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    basal_time_button_api_demo_basal_time_post: {
        parameters: {
            query?: never;
            header?: {
                "X-PIN"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
